### ISSUE TITLE
any has successfully run SE on Wine? [GNU/Linux]

### ISSUE THREAD

**Issue by tariq0101** [SubtitleEdit/subtitleedit#8124]
mono doesn't render RTL languages correctly so I'm trying to run Subtitle Edit on wine.
I successfully launched the program after installing wine-mono and dxd and dotnet.
everything is apparently working correctly as windows, except that the video doesn't show at all, only the audio of the video is heard.
I tried mpv, directshow, and VLC, all have the exact same problem.
if anyone knows how to use RTL languages on mono or how to run SE on wine. please do share.
Edit: I just tried MPC. also the same issue.

**Comment by tariq0101** [comment]
I got it working pretty well using lutris.
I'll post the script on Lutris and link it here. 
I'll close this issue after posting the link.

**Comment by tariq0101** [comment]
copy this YAML code and paste it in an empty file and use it to install SE.
`
```

files:
- subeditzip: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SE404.zip
- vlc: https://get.videolan.org/vlc/3.0.16/win32/vlc-3.0.16-win32.exe
game:
  arch: win32
  exe: $GAMEDIR/drive_c/subtitleedit/SubtitleEdit.exe
  prefix: $GAMEDIR
installer:
- extract:
    description: Unzipping subtitle edit
    dst: $GAMEDIR/drive_c/subtitleedit
    src: subeditzip
- task:
    args: /S
    description: Installing VLC
    executable: vlc
    name: wineexec
    prefix: $GAMEDIR
- task:
    app: d3dx9
    description: Installing Direct3D 9
    name: winetricks
    prefix: $GAMEDIR
- task:
    app: dotnet48
    description: Installing .NET 4.8 runtime
    name: winetricks
    prefix: $GAMEDIR

description: Subtitle Edit 4.0.4 installer
game_slug: subtitle-edit4
gogslug: ''
humblestoreid: ''
installer_slug: subtitle-edit-404
name: Subtitle Edit4
notes: 'Note: After you install this, go to Options->Settings->Video Player->Download
  mpv lib, download it and set the video to direct3d, then choose mpv as your Video
  engine.'
runner: wine
script:
  files:
  - subeditzip: https://github.com/SubtitleEdit/subtitleedit/releases/download/4.0.4/SE404.zip
  - vlc: https://get.videolan.org/vlc/3.0.16/win32/vlc-3.0.16-win32.exe
  game:
    arch: win32
    exe: $GAMEDIR/drive_c/subtitleedit/SubtitleEdit.exe
    prefix: $GAMEDIR
  installer:
  - extract:
      description: Unzipping subtitle edit
      dst: $GAMEDIR/drive_c/subtitleedit
      src: subeditzip
  - task:
      args: /S
      description: Installing VLC
      executable: vlc
      name: wineexec
      prefix: $GAMEDIR
  - task:
      app: d3dx9
      description: Installing Direct3D 9
      name: winetricks
      prefix: $GAMEDIR
  - task:
      app: dotnet48
      description: Installing .NET 4.8.0 runtime
      name: winetricks
      prefix: $GAMEDIR
slug: subtitle-edit-404
steamid: null
version: 4.0.4
year: 2024

```
``
