### ISSUE TITLE
AllTalks TTS - Getting Output Error

### ISSUE THREAD

**Issue by FrogChopi** [SubtitleEdit/subtitleedit#8608]
Hello,
I try to use All Talks because results are pretty good ( i use the docker image ),
When Substitle edit request the api it work well ( the output is generated and work well ) but it try to get it on... a linux path ( i'm on windows ) ?
```dotnet
'/app/outputs/output.wav'.
   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   à Nikse.SubtitleEdit.Forms.Tts.TextToSpeech.GenerateParagraphAudioAllTalk(Subtitle subtitle, Boolean showProgressBar, String overrideFileName)
   à Nikse.SubtitleEdit.Forms.Tts.TextToSpeech.buttonTestVoice_Click(Object sender, EventArgs e)
```
It would be possible to specify the output path where subtitleedit fetches the file ( I may have missed the config )

**Comment by niksedk** [comment]
SE probably only works with this method:

1) use git to clone the repro: `git clone https://github.com/erew123/alltalk_tts.git`
2) use the setup bat file: `atsetup.bat` (choose "standalone")
3) start with "start_alltalk.bat"

Note that you can get more voices here: 
https://drive.google.com/file/d/1bYdZdr3L69kmzUN3vSiqZmLRD7-A3M47/view?usp=drive_link
https://drive.google.com/file/d/1CPnx1rpkuKvVj5fGr9OiUJHZ_e8DfTzP/view

**Comment by FrogChopi** [comment]
I like docker because I'm a bit lazy ^^
I'll do that :) Thank you for your reply and for the great work you do.

**Comment by niksedk** [comment]
You're welcome :)

What docker command did you use?  (I'm lazy too)

**Comment by FrogChopi** [comment]
- `git clone https://github.com/erew123/alltalk_tts.git && cd alltalk_tts`
- Personally i use an prebuilt image :
    ```yml
    version: '3.8'
    services:
      alltalk-tts:
        image: joshxt/alltalk_tts:cuda # you can replace by build : . if you want to built yourself
        restart: unless-stopped
        ports:
          - "7851:7851"
        volumes:
          - ./outputs:/app/outputs/
          - ./models:/app/models/
          - ./voices:/app/voices/
          - ./finetune/put-voice-samples-in-here:/app/finetune/put-voice-samples-in-here
          - ./dockerconfig.json:/app/confignew.json
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: all
                  capabilities: [ gpu ]
    ```
- `docker-compose --file docker-compose-cuda.yml up -d`
- Now you can just : `curl -X POST "http://localhost:7851/api/tts-generate-streaming" -d "text=\"I'll be back\" is a catchphrase associated with Arnold Schwarzenegger. It was made famous in the 1984 science fiction film The Terminator." -d "voice=arnold.wav" -d "language=en" -d "output_file=myoutputfile.wav" -d "streaming=false"`
- Result in `./outputs`
